---
title: "Decision_Trees_Bank_Loans"
author: "Ashley Bischof"
output: html_document
---

#Develop a simple credit approval model using C5.0 decision trees:

## Prepare and Clean Data

```{r}
credit = read.csv("~/Dropbox/R ref/Machine Learning with R/chapter 5/credit.csv")

str(credit)

table(credit$checking_balance)
table(credit$savings_balance)

summary(credit$months_loan_duration)
summary(credit$amount)

table(credit$default)
```


Randomize and choose training (90%) and test (10%) dataset
```{r}
set.seed(12345)
credit_rand = credit[order(runif(1000)), ]

#chek that randomized stats are still the same but order is different
summary(credit$amount)
summary(credit_rand$amount)
head(credit$amount)
head(credit_rand$amount)

#split into train and test dataset
credit_train = credit_rand[1:900, ]
credit_test = credit_rand[901:1000, ]

#check that ~30% of defaulted loans are in each dataset
prop.table(table(credit_train$default))
prop.table(table(credit_test$default))
```


#Train the Model - first attempt (using C5.0 C50 package)
```{r}
library(C50)
credit_model = C5.0(credit_train[-17], credit_train$default)

credit_model
summary(credit_model)
```

#Test Model Performance
```{r}
credit_pred = predict(credit_model, credit_test)

library(gmodels)
CrossTable(credit_test$default, credit_pred, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual default', 'redicted default'))
```


#Improve and Retrain the Model with Boosting
```{r}
credit_boost10 = C5.0(credit_train[-17], credit_train$default, trials = 10)

credit_boost10
summary(credit_boost10)

credit_boost_pred10 = predict(credit_boost10, credit_test)
CrossTable(credit_test$default, credit_boost_pred10, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual default', 'redicted default'))
```


#Making some mistakes more costly
```{r}
error_cost = matrix(c(0,1,4,0), nrow = 2)
error_cost

credit_cost = C5.0(credit_train[-17], credit_train$default, costs = error_cost)
credit_cost_pred = predict(credit_cost, credit_test)
CrossTable(credit_test$default, credit_cost_pred, prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE, dnn = c('actual default', 'predicted default'))
```




